# Generated by Django 2.2.17 on 2025-09-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='topLevelDomain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
