# Generated by Django 2.2.17 on 2025-09-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20250901_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='topLevelDomain',
            new_name='topleveldomain',
        ),
    ]
